# Указываем, что наш проект на Java
language: java

# Версия JDK, которую Travis будет использовать для сборки
jdk:
  - openjdk17

# Travis автоматически выполнит 'mvn test'
# Эта настройка понадобится, если мы захотим выполнить что-то особенное
script:
  - mvn clean test

# Настройка для кэширования, чтобы ускорить последующие сборки
cache:
  directories:
    - $HOME/.m2